# Module constants

START_X = 0
START_Y = 0
START_ANGLE = 0

STRAIGHT_TRACK = "STRAIGHT TRACK"
SIZE_OF_STRAIGHT_TRACK = 3

CURVED_TRACK = "CURVED TRACK"
SIZE_OF_CURVED_TRACK = 2

DIVERGENT_TRACK = "DIVERGENT TRACK"
CONVERGENT_TRACK = "CONVERGENT TRACK"
